#!/usr/bin/env python3
"""Generate docs/CATALOG.md from each skill's SKILL.md frontmatter.

Single source of truth: the `name` and `description` fields in
skills/<name>/SKILL.md. Re-run after adding, renaming, or re-describing a skill:

    python3 scripts/gen-catalog.py

No third-party dependencies (stdlib only), so it runs anywhere Python 3 does.
"""
from __future__ import annotations

import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
SKILLS = REPO / "skills"
OUT = REPO / "docs" / "CATALOG.md"


def read_frontmatter(skill_md: pathlib.Path) -> dict[str, str]:
    """Parse the leading --- ... --- YAML block. Stops at the closing fence so
    stray `description:` lines in the body are never picked up."""
    text = skill_md.read_text(encoding="utf-8").splitlines()
    if not text or text[0].strip() != "---":
        return {}
    fields: dict[str, str] = {}
    for line in text[1:]:
        if line.strip() == "---":
            break
        if ":" in line and not line.startswith((" ", "\t")):
            key, _, val = line.partition(":")
            fields[key.strip()] = _unquote(val.strip())
    return fields


def _unquote(s: str) -> str:
    if len(s) >= 2 and s[0] == s[-1] and s[0] in "\"'":
        return s[1:-1]
    return s


def first_sentence(desc: str) -> str:
    """First sentence: cut at the first '. ' that isn't an abbreviation like
    '.excalidraw'. Good enough for a one-line purpose column."""
    i = desc.find(". ")
    return (desc[: i + 1] if i != -1 else desc).strip()


def bundled_summary(skill_dir: pathlib.Path) -> str:
    """Short note on what ships alongside SKILL.md (top-level dirs only)."""
    subdirs = sorted(
        p.name for p in skill_dir.iterdir() if p.is_dir() and p.name != "__pycache__"
    )
    return ", ".join(f"`{d}/`" for d in subdirs) if subdirs else "—"


def main() -> int:
    skills = sorted(p for p in SKILLS.iterdir() if (p / "SKILL.md").exists())
    if not skills:
        print("no skills found under skills/", file=sys.stderr)
        return 1

    rows, sections = [], []
    for d in skills:
        fm = read_frontmatter(d / "SKILL.md")
        name = fm.get("name", d.name)
        desc = fm.get("description", "")
        rows.append(f"| [`{name}`](../skills/{d.name}/SKILL.md) | {first_sentence(desc)} |")
        sections.append(
            f"### `{name}`\n\n"
            f"{desc}\n\n"
            f"**Bundled:** {bundled_summary(d)}\n"
        )

    md = [
        "# Skill catalog",
        "",
        "_Generated by `scripts/gen-catalog.py` — do not edit by hand; "
        "edit the `description` in each `skills/<name>/SKILL.md` and re-run._",
        "",
        f"**{len(skills)} skills** in this collection.",
        "",
        "| Skill | Purpose |",
        "|-------|---------|",
        *rows,
        "",
        "---",
        "",
        "## Full descriptions",
        "",
        *sections,
    ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(md).rstrip() + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)} ({len(skills)} skills)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
